---
# tasks/configuration file for deb-base
- name: Configruation | Set ssh template file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  become: true

- name: Configuration | Set MotD requirements
  apt:
    pkg: 'figlet'
    state: present
    update_cache: true
- name: Configuration | Set MotD
  copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: 0644
  
