---
# tasks/install file for deb-base

- name: Install | Ensure core packages are installed
  apt:
    pkg: "{{ install_core_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid }}"

- name: Install | Ensure core packages are removed
  apt:
    pkg: "{{ remove_core_packages }}"
    state: absent

- name: Install | Ensure specified packages are installed
  apt:
    pkg: "{{ install_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid }}"

- name: Install | Ensure specified packages are removed
  apt:
    pkg: "{{ remove_packages }}"
    state: absent
